// Generator functions for Veil CLI

export function generateConfig(
  useHelius: boolean,
  useShadowPay: boolean,
  template: string
): string {
  const features = {
    basic: ['identity', 'recovery'],
    governance: ['identity', 'recovery', 'voting'],
    treasury: ['identity', 'recovery', 'multisig'],
    full: ['identity', 'recovery', 'voting', 'multisig', 'staking'],
  };

  const enabledFeatures = features[template as keyof typeof features] || features.basic;

  return `// Veil Protocol Configuration
// Generated by @veil-protocol/cli

import type { VeilConfig } from '@veil-protocol/sdk';

export const config: VeilConfig = {
  // Network configuration
  network: 'devnet', // 'devnet' | 'mainnet-beta'
  
  // Program ID (Aegis Shield core)
  programId: '5C1VaebPdHZYETnTL18cLJK2RexXmVVhkkYpnYHD5P4h',
  
  // RPC Configuration
  rpc: {
    provider: '${useHelius ? 'helius' : 'default'}',
    ${useHelius ? "// Privacy note: Using Helius RPC to avoid public polling and reduce metadata leakage" : '// Consider using Helius for better privacy'}
    ${useHelius ? "endpoint: process.env.HELIUS_RPC_URL || 'https://devnet.helius-rpc.com/?api-key=' + process.env.HELIUS_API_KEY," : "endpoint: 'https://api.devnet.solana.com',"}
  },
  
  // Enabled features
  features: {
    identity: ${enabledFeatures.includes('identity')},
    recovery: ${enabledFeatures.includes('recovery')},
    voting: ${enabledFeatures.includes('voting')},
    multisig: ${enabledFeatures.includes('multisig')},
    staking: ${enabledFeatures.includes('staking')},
  },
  
  // External integrations
  integrations: {
    // ShadowPay: Private value transfer via ShadowWire
    shadowPay: ${useShadowPay}, // Enable for private value transfer (Radar Hackathon eligible)
    
    // Helius: Privacy-focused RPC
    helius: ${useHelius},
  },
  
  // Recovery settings
  recovery: {
    timelockSeconds: 86400, // 24 hours
    minGuardians: 2,
    maxGuardians: 5,
  },
  
  // Voting settings
  voting: {
    defaultVotingPeriod: 259200, // 3 days in seconds
    defaultRevealPeriod: 86400, // 1 day in seconds
  },
};

export default config;
`;
}

export function generateRpcAbstraction(useHelius: boolean): string {
  return `// Privacy-focused RPC abstraction
// Generated by @veil-protocol/cli

import { Connection, clusterApiUrl } from '@solana/web3.js';

/**
 * Privacy note:
 * ${useHelius 
    ? 'Using Helius RPC to avoid public polling and reduce metadata leakage.\n * Helius provides better privacy than public RPC endpoints.' 
    : 'Consider using Helius RPC for better privacy - reduces metadata leakage from public endpoints.'}
 * 
 * Why this matters:
 * - Public RPC endpoints can log your IP + wallet associations
 * - Request patterns can reveal user behavior
 * - Helius provides dedicated endpoints with better privacy practices
 */

const HELIUS_API_KEY = process.env.HELIUS_API_KEY;
const NETWORK = process.env.VEIL_NETWORK || 'devnet';

function getRpcEndpoint(): string {
  ${useHelius ? `// Helius RPC (recommended for privacy)
  if (HELIUS_API_KEY) {
    const cluster = NETWORK === 'mainnet-beta' ? 'mainnet' : 'devnet';
    return \`https://\${cluster}.helius-rpc.com/?api-key=\${HELIUS_API_KEY}\`;
  }
  
  console.warn('[Veil] HELIUS_API_KEY not set - falling back to public RPC (less private)');` : `// Public RPC endpoint
  // Consider setting HELIUS_API_KEY for better privacy`}
  
  return clusterApiUrl(NETWORK as 'devnet' | 'mainnet-beta');
}

// Singleton connection with privacy-optimized settings
let connection: Connection | null = null;

export function getConnection(): Connection {
  if (!connection) {
    connection = new Connection(getRpcEndpoint(), {
      commitment: 'confirmed',
      // Disable WebSocket to reduce metadata leakage
      wsEndpoint: undefined,
    });
  }
  return connection;
}

export function resetConnection(): void {
  connection = null;
}

export { Connection };
`;
}

export function generatePackageJson(projectName: string): object {
  return {
    name: projectName,
    version: '0.1.0',
    description: 'A Veil Protocol privacy-first Solana application',
    scripts: {
      dev: 'vite',
      build: 'tsc && vite build',
      preview: 'vite preview',
    },
    dependencies: {
      '@solana/web3.js': '^1.87.0',
      '@veil-protocol/sdk': '^0.1.0',
    },
    devDependencies: {
      typescript: '^5.3.2',
      vite: '^5.0.0',
    },
  };
}

